FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm config set registry https://registry.npm.taobao.org
RUN npm set sass_binary_site=https://npm.taobao.org/mirrors/node-sass/
RUN npm config set @mediinfo-ued:registry http://172.19.30.181:8081/repository/npm-main
COPY . .
RUN npm  install
RUN npm run build -- --mode testing

FROM nginx
COPY --from=build-stage /app/dist-test/  /usr/share/nginx/html/
COPY nginx-single.conf /etc/nginx/nginx.conf
RUN echo 'echo init ok!!'

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
